### ISSUE TITLE
Best way to keep "lang" parameter?

### ISSUE THREAD

**Issue by GreWull** [adonisjs/adonis-antl#12]
I was wondering what's the best way to handle the lang parameter. 

What I would like to do is to have some links for selecting the language, and once the user clicked all the other pages will also use that language.

Any tips?

**Comment by GreWull** [comment]
This is my implementation right now I don't really like it.

2 links and 1 route that set in a session variable the language.

```
<a  href="./setLanguage?lang=it">Italiano</a>
<a href="./setLanguage?lang=en">English</a>

  * setLanguage (request, response) {
    yield request.session.put('lang', request.input('lang'))
    response.redirect('back')
  }
```

Then I have a global Middleware that check if the language has been changed, and redirects to the correct url with the `lang ` parameter

```
* handle (request, response, next) {
    const lang = yield request.session.get('lang')

    if (request.url() != '/setLanguage' && lang != request.input('lang')) {
    	response.redirect(request.url() + '?lang=' + lang)
    	return
    }
    yield next
  }
```

It works but it feels wrong to do something like this!

**Comment by RomainLanz** [comment]
Hey @GreWull! 👋 

Now Adonis got [a forum](https://forum.adonisjs.com/), it would be nice to move your question to this forum since it's not a direct issue with `adonis-antl`.
