### ISSUE TITLE
Valid ICU String causing MISSING_OTHER_CLAUSE

### ISSUE THREAD

**Issue by IgoP02** [adonisjs/adonis-antl#135]
### Package version

1.6.0

### Describe the bug

Using the ICU select syntax with any string throws a `MISSING_OTHER_CLAUSE` exception.

I have the following ICU string which I have tested with other formatters. 

``Subject {name} status has been updated to {status, select, 1 {accepted} -2 {rejected} -3 {set for revision} other {other}}.``

But running ``i18n.formatMessage(`Subject {name} status has been updated to {status, select, 1 {accepted} -2 {rejected} -3 {set for revision} other {other}}.`, {name: 'Test', status: -3 })`` will throw the following exception.

    err: {
      "type": "SyntaxError",
      "message": "MISSING_OTHER_CLAUSE",
      "stack":
          SyntaxError: MISSING_OTHER_CLAUSE
             {{...rest of the  stack}}
      "location": {
        "start": {
          "offset": 72,
          "line": 1,
          "column": 73
        },
        "end": {
          "offset": 72,
          "line": 1,
          "column": 73
        }
      },

UPDATE: Removing the hyphens from the keys fixes the issue. Is this normal behavior with ICU syntax?

**Comment by RomainLanz** [comment]
Hey @IgoP02! 👋🏻 

Are you saying it works with other ICU parsers but not ours?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
