### ISSUE TITLE
Translating validation messages

### ISSUE THREAD

**Issue by effectjared** [adonisjs/adonis-antl#15]
Is there a way to provide translations for validation messages with Antl?
We would like to set up a validation.json file in resources/locales/ with our custom messages in.
Can we do this without manually passing the messages through each time we use the validator? Can't find anything in the docs on this.

**Comment by thetutlage** [comment]
@effectjared Unfortunately there is no way to define validation messages within a seperate locales file. What you can do is use the `antl` provider to set the messages. Here is an example

```js
function getMessages (locale) {
  return {
    'email.required': Antl.for(locale).get('validations.email.required')
  }
}
```

And then use `getMessages` method to get messages for a given validation cycle.

I know this can be supported by Adonis itself, which I am going to do soon, but for now this is the best and ideal way to do it

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
