### ISSUE TITLE
Translating auth error messages ?

### ISSUE THREAD

**Issue by alanaasmaa** [adonisjs/adonis-antl#22]
Hello, how can i translate error messages ? 

Do i have to check what error it is and then throw message accordingly ?
```
try {
      yield request.auth.attempt(userData.email, userData.password)
    } catch (e) {
      response.json({
        errors: e.message
      })
      return
    }
```

**Comment by RomainLanz** [comment]
Hey @alanaasmaa ! 👋 

Sorry for the late reply.
You can simply use the code of the error to fetch the translation you want.

**Comment by alanaasmaa** [comment]
@RomainLanz Thanks i will try it ! I have other things on the way so i can't do it right now. I will close it cause it won't feel like a issue.

**Comment by RomainLanz** [comment]
Great !

Feel free to open a thread on the forum if you struggle somewhere https://forum.adonisjs.com/ 😄
