### ISSUE TITLE
Can't switch locale on run time

### ISSUE THREAD

**Issue by lhmboyz** [adonisjs/adonis-antl#25]
Hi,

Why i can't switch locale on run time, i setup this on `config/app.js`:

`
locales: {
    driver: 'file',
    locale: 'id'
}`

and then i try to switch the locale to `en` using this syntax on run time:

`Antl.setLocale('en')`

`Antl.formatMessage('messages.EMAIL_LOGIN_SUCCEEDED')`

but here is the result, still stuck on `id` locale:

`Login email berhasil`

**Comment by lhmboyz** [comment]
On previous release, i use this syntax to change the locale:

`Antl.setLocale('en')`

But this can't work anymore on current release.
Thank you.

**Comment by thetutlage** [comment]
Read the docs here http://dev.adonisjs.com

**Comment by lhmboyz** [comment]
Wow, thanks friend, it's worked now.
