### ISSUE TITLE
Change language problem.

### ISSUE THREAD

**Issue by sequendnb** [adonisjs/adonis-antl#26]
Hi there! I try to change language by controller. Let's see.. 

**LanguageController.js**

```
'use strict'

const Antl = use('Antl')

class LangController {

  async en ({antl, view}) {
    antl.switchLocale('en')
    return view.render('layout.app')
  }

  async ru ({antl, view}) {
    antl.switchLocale('ru')
    return view.render('layout.app')
  }
}

module.exports = LangController
```

**Routes.js**

```
Route.group(() => {
  Route.get('/en', 'LangController.en')
  Route.get('/ru', 'LangController.ru')
}).middleware(['auth','guest'])
```

..and call text strings in views:

`{{ antl.formatMessage('menu.signin') }}`

Result: can't switch language. Default locale is 'en', but at the views i see 'ru' locales.

Can you help me with this? Thank you.

**Comment by sequendnb** [comment]
All code you can check in my repo: [https://github.com/sequendnb/AdonisJS-4-App](url)

**Comment by thetutlage** [comment]
Replied on the forum thread https://forum.adonisjs.com/t/adonisjs-antl-cant-switch-locale/571
