### ISSUE TITLE
Message key level. More than 2 depth.

### ISSUE THREAD

**Issue by respirer2** [adonisjs/adonis-antl#32]
I wanna use more than 2 depth message keys. (for example, home.slide.top_text)
But, adonis-antl doesn't support this.
Is it intended? or bug?

I looked around the Antl sources. 
I guess, in the Antl class, the 'get' method in 'Antl class' forces to make the hierarchy two depth.

    get (key, defaultValue = null) {
      const [group, ...parts] = key.split('.')
      const messageKey = parts.join('.')

      /**
       * Look for the message inside the locale message
       * and under a certain group.
       *
       * @type {Array}
       */
      const localeNode = [this._locale, group, messageKey]

      /**
       * The fallback node is used when value has not been found
       * inside the local node
       *
       * @type {Array}
       */
      const fallbackKey = this._messages['*'] ? '*' : 'fallback'
      const fallbackNode = [fallbackKey, group, messageKey]

      debug('getting message for %s key from store', localeNode.join('.'))
      debug('using fallback key as %s', fallbackNode.join('.'))

      return _.get(this._messages, localeNode, _.get(this._messages, fallbackNode, defaultValue))
    } 

I've changed the 'get' method in Antl class as following. Then, it supports more than 2 depth message keys.

    get (key, defaultValue = null) {
      const [group, ...parts] = key.split('.') 

      /**
       * Look for the message inside the locale message
       * and under a certain group.
       *
       * @type {Array}
       */
      let localeNode = [this._locale, group]
      localeNode = localeNode.concat(parts)
    
      /**
       * The fallback node is used when value has not been found
       * inside the local node
       *
       * @type {Array}
       */
      const fallbackKey = this._messages['*'] ? '*' : 'fallback'
      let fallbackNode = [fallbackKey, group]
      fallbackNode = fallbackNode.concat(parts)

      debug('getting message for %s key from store', localeNode.join('.'))
      debug('using fallback key as %s', fallbackNode.join('.'))

      return _.get(this._messages, localeNode, _.get(this._messages, fallbackNode, defaultValue))
    }

**Comment by thetutlage** [comment]
For now, we only allow flat structure and you can use, dot notation to scope messages

```
"user.age": ""
```

**Comment by respirer2** [comment]
Thanks for your answer. 
Then.. no plan to support it?

**Comment by thetutlage** [comment]
@respirer2 Nope not for now. Since the format has to be portable to other storage engines too. Which is `database` for now

**Comment by respirer2** [comment]
@thetutlage Aha~ OK Thanks~
