### ISSUE TITLE
Reload the language file.

### ISSUE THREAD

**Issue by xyz-systems** [adonisjs/adonis-antl#87]
## Prerequisites

I need to reload language file from file loader. I am using adonis 4.1. where as this feature was available in 3.2 Legacy version.
But in this 4.1 there is no functionliaty for that 

## Why this feature is required (specific use-cases will be appreciated)?
This feature is require to add literal dynamically and reload the them to cache. which is not done in the version of adonis 4.1.

## Have you tried any other work arounds?
Yes i tried a lot of methods but not finding this thing. Even i have emailed harminder virk. who developed adonis as well as this package. 
## Are you willing to work on it with little guidance?
Yes.

**Comment by thetutlage** [comment]
You can reload using the `reload` method.

```js
Antl.loader('file').reload()
```

**Comment by xyz-systems** [comment]
> You can reload using the `reload` method.
> 
> ```js
> Antl.loader('file').reload()
> ```

i have tried this one but its not working...

even i have tried await Antl.bootLoader('file')

can you please help me i can show you what exactly i am doing ...

**Comment by xyz-systems** [comment]
> i have found load functon inside `/node_modules/@adonisjs/antl/src/Loaders/File.js` is using `requireAll`

> ```js
  load () {
    debug('loading strings from file system %s', this._config.localesDir)

    return requireAll({
      dirname: this._config.localesDir,
      filters: /(.*)\.json$/
    })
  }
>```

which is not loading the latest literals from file.

Is there any solution ? Please help me for this @thetutlage

**Comment by thetutlage** [comment]
Fixed. Please try installing the new version with the `legacy` tag

```sh
npm i @adonisjs/antl@legacy
```

**Comment by xyz-systems** [comment]
> Fixed. Please try installing the new version with the `legacy` tag
> 
> ```shell
> npm i @adonisjs/antl@legacy
> ```

when you are going to release it from legacy to stable branch @thetutlage ?

**Comment by thetutlage** [comment]
The v4 packages will always be behind the `legacy` tag. The `latest` tag is reserved for v5

**Comment by xyz-systems** [comment]
thanks
